{
 "title": "Network",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "first_timestamp", "query": "${VAR_FIRST_TIMESTAMP}" },
   {
    "name": "Interval",
    "query": "1h : 3600, 6h : 21600, 1d : 86400"
   },
   {
    "name": "Blocks",
    "query": {
     "query": "query_result(${Interval} / monero_network_target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transaction rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time() - $first_timestamp > bool ${Interval}) * delta(monero_network_tx_count[${Interval}s]) / ${Interval}",
     "legendFormat": "Avg tx/s - last ${Interval:text}"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "si:" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(monero_network_difficulty[${Interval}s])",
     "legendFormat": "Avg difficulty - last ${Interval:text}"
    }
   ]
  },
  {
   "title": "Hash rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "(time() - $first_timestamp > bool ${Interval}) * avg_over_time(monero_network_difficulty[${Interval}s]) * rate(monero_network_height[${Interval}s])",
     "legendFormat": "Avg hash rate - last ${Interval:text}"
    },
    {
     "expr": "avg_over_time(monero_network_difficulty[${Interval}s]) / monero_network_target",
     "legendFormat": "Target hash rate"
    }
   ]
  },
  {
   "title": "Block time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "suffix:s" }
   ],
   "targets": [
    {
     "expr": "(time() - $first_timestamp > bool ${Interval}) / rate(monero_network_height[${Interval}s])",
     "legendFormat": "Avg block time - last ${Interval:text}"
    },
    { "expr": "monero_network_target", "legendFormat": "Target block time" }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "monero_blocks_avg_size{block_count=\"${Blocks}\"}",
     "legendFormat": "Avg block size - last ${Blocks} blocks"
    },
    {
     "expr": "monero_blocks_max_size{block_count=\"${Blocks}\"}",
     "legendFormat": "Max block size - last ${Blocks} blocks"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "monero_blocks_avg_txes{block_count=\"${Blocks}\"}",
     "legendFormat": "Avg tx/block - last ${Blocks} blocks"
    },
    {
     "expr": "monero_blocks_max_txes{block_count=\"${Blocks}\"}",
     "legendFormat": "Max tx/block - last ${Blocks} blocks"
    }
   ]
  },
  {
   "title": "Reward",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "si:ɱ" }
   ],
   "targets": [
    {
     "expr": "monero_blocks_avg_reward{block_count=\"${Blocks}\"} * 1e-12",
     "legendFormat": "Avg ɱ/block - last ${Blocks} blocks"
    },
    {
     "expr": "monero_blocks_max_reward{block_count=\"${Blocks}\"} * 1e-12",
     "legendFormat": "Max ɱ/block - last ${Blocks} blocks"
    }
   ]
  }
 ]
}