{
 "title": "Node",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Transaction pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_txpool_bytes_total[$__interval])",
     "legendFormat": "Max pool size"
    },
    {
     "expr": "max_over_time(monero_txpool_txs_total[$__interval])",
     "legendFormat": "Max tx count"
    }
   ]
  },
  {
   "title": "Transaction sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(monero_txpool_bytes_med[$__interval])",
     "legendFormat": "Median tx size"
    },
    {
     "expr": "max_over_time(monero_txpool_bytes_max[$__interval])",
     "legendFormat": "Max tx size"
    }
   ]
  },
  {
   "title": "Delayed transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_txpool_txs_above_10min[$__interval])",
     "legendFormat": "Txs older than 10 min"
    }
   ]
  },
  {
   "title": "Not relayed transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_txpool_txs_not_relayed[$__interval])",
     "legendFormat": "Not relayed txs"
    }
   ]
  },
  {
   "title": "Double spend transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_txpool_double_spends[$__interval])",
     "legendFormat": "Double spend txs"
    }
   ]
  },
  {
   "title": "Failing transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_txpool_txs_failing[$__interval])",
     "legendFormat": "Failing txs"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Database size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_node_database_size[$__interval])",
     "legendFormat": "Database size"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min_over_time(monero_node_free_space[$__interval])",
     "legendFormat": "Free space"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Incoming connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_node_incoming_connections_count[$__interval])",
     "legendFormat": "Incoming connections"
    }
   ]
  },
  {
   "title": "Outgoing connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_node_outgoing_connections_count[$__interval])",
     "legendFormat": "Outgoing connections"
    }
   ]
  },
  {
   "title": "RPC connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_node_rpc_connections_count[$__interval])",
     "legendFormat": "RPC connections"
    }
   ]
  },
  { "title": "Peerlists", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "White peerlist size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_node_white_peerlist_size[$__interval])",
     "legendFormat": "White peerlist size"
    }
   ]
  },
  {
   "title": "Grey peerlist size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(monero_node_grey_peerlist_size[$__interval])",
     "legendFormat": "Grey peerlist size"
    }
   ]
  }
 ]
}